version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
environment:
  configuration: Release
  COVERALLS_REPO_TOKEN:
    secure: PgqGX/MKkBHptwqnLx5PvnPxIBQ/zRryi/1q/WrQ5RYmFv/7rWrWfQybg17g4FaK
build_script:
  - ps: dotnet build -c Release
test: on
test_script:
  - test.cmd
